name: 'Cherry Picker'
description: 'Cherry pick pull request commits into releases.'
inputs:
  token:
    description: 'Github token.'
    required: true
  pull_number:
    description: 'Number of the Github pull request.'
    required: true
  slack_webhook:
    description: 'Slack webhook for messages.'
    required: false
outputs:
  cherry_picks:
    description: 'Stringified JSON array detailing the status of the cherry pick attempts.'
runs:
  using: 'node16'
  main: 'index.js'
