name: 'Semantic Version Bump and Tag'
description: 'Takes an array of github tag objects, and determines the major, minor, or patch version to bump. then creates the tag'
inputs:
  token:
    description: 'Github token.'
    required: true
  bump:
    description: 'Choose between `major`, `minor` or `patch`.'
    required: true
  major:
    description: Filter tags for `major`.
    required: false
  minor:
    description: Filter tags for minor, must be using `major` input too.
    required: false
  prefix:
    description: Prefix for the resulting tag.
    required: false
    default: 'v'
  suffix:
    description: Suffix for the resulting tag.
    required: false
    default: 'v'
outputs:
  tag:
    description: 'The created tag.'
runs:
  using: 'node16'
  main: 'index.js'
